


export  const data={
"local":[
    {id: 1, title: 'Pinddaan at Gaya', des:"It was at this place, sitting under a tree Gautama Buddha attained enlightenment about 2600 years back. This quaint and divine town is therefore an important pilgrimage spot for the Buddhists. Visit its beautiful monasteries and temples and just experience the warmth and serenity like never before.", content: 'from $1100 per group', imgUrl: 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/1a/60/74/be/caption.jpg?w=300&h=300&s=1'},
    {id: 2, title: 'Full-Day Bodh Gaya Private Tour', content: 'from $1300 per adult', imgUrl: 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/1b/38/28/af/caption.jpg?w=300&h=300&s=1',des:"Ideal for travelers interested in immersive experiences and Buddhism, this comprehensive tour explores key sacred Buddhist sites between Varanasi to Lucknow over 12 days of sightseeing. Highlights include a morning boat ride on the Ganges River and visiting stupa structures—thought to hold relics of the Buddha—and archeological sites where Buddha is believed to have been born, met his disciples, and attained enlightenment. Transportation and accommodation for 11 nights with breakfast are included."},
    {id: 3, title: 'Nalanda Rajgir and Bodh Gaya from Patna', content: 'from $1340 per adult', imgUrl: 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/1a/f8/2a/bf/caption.jpg?w=300&h=300&s=1',des:"Leave Patna and visit home of Nalanda and Rajgir. This visit includes heritage buildings such as the one of the world's historic universities. Explore the hills of Ratnagiri where the Lord Budda gave sermons in the local Bhuddist caves. Visit the Venuvanaram and Bimbisara Prison before staying overnight in Bodh Gaya. Finish the adventure at the Maha Bodhi Temple which features Bodhi Trees and the Janki Temple."},
    {id: 4, title: 'Buddhist Tour From The Birth To Death', content: 'from $1500 per adult', imgUrl: 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/1a/5f/26/24/caption.jpg?w=300&h=300&s=1',des:"Ideal for travelers interested in immersive experiences and Buddhism, this comprehensive tour explores key sacred Buddhist sites between Varanasi to Lucknow over 12 days of sightseeing. Highlights include a morning boat ride on the Ganges River and visiting stupa structures—thought to hold relics of the Buddha—and archeological sites where Buddha is believed to have been born, met his disciples, and attained enlightenment. Transportation and accommodation for 11 nights with breakfast are included."},
    {id: 5, title: 'Historic Gurudwara Tour Of Patna', content: 'from $5500 per adult', imgUrl: 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/1a/9f/cb/6a/caption.jpg?w=300&h=300&s=1',des:"Four sacred sites associated with Lord Buddha Life, that a pious person should visit and look upon with feelings of reverence. LUMBINI ‘Here the Tathagata [the one who has gone beyond all transitory phenomena] was born.’ BODHGAYA ‘Here the Tathagata became fully enlightened.’ SARNATH ‘Here the Tathagata set in motion the wheel of the dhamma.’ KUSHINAGAR ‘Here the Tathagata passed away into the state of nirvana in which no element of clinging remains!’ And the monk, the nun, the layman or laywoman who has faith should visit these places. And whoever, should die on such a pilgrimage with his heart established in faith, at the breaking up of the body after death will be reborn in a realm of heavenly happiness."},
    {id: 6, title: 'Full Sacred Sites Associated With Lord Buddha ', content: 'from $5000 per adult', imgUrl: 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/1a/5f/5f/77/caption.jpg?w=300&h=300&s=1'},
    {id: 7, title: 'Jain Spiritual Tour', content: 'from $6000 per adult', imgUrl: 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/1b/40/48/d3/caption.jpg?w=300&h=300&s=1',des:"Embark on this pilgrimage tour designed for followers of Jainism. Leave from Patna and head towards the temples of Vaishali to appreciate the holy birthplace of Lord Mahavira. Roam further towards the Nalanda region to visit the ruins of Nalanda University, a UNESCO World Heritage Site. Finish at Sammed Shikharji that perches on top of Parasnath Hill. This is a unique chance to follow in the footsteps of Tirthankaras."},
    {id: 8, title: 'Deoghar Baidyanath Dham From Patna', content: 'from $7000 per adult', imgUrl: 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/1b/40/63/ba/caption.jpg?w=300&h=300&s=1'},
    {id: 9, title: 'Spiritual Tour of Bodh Gaya & Varanasi', content: 'from $9000 per adult', imgUrl: 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/1a/60/87/ec/caption.jpg?w=300&h=300&s=1'},
   
  ],
  "abroad":[
    {id: 10, title: 'Bangkok,Thailand', des:"There are cities and then there is Bangkok. Temples like Wat Pho are thronged with devotees all day. Street food sizzles all evening. The heat never stops. And the nightlife—from sleazy Patpong to ritzy rooftop bars—is second to none. But the pleasures don’t end there. Night markets, mega malls, and the massive Chatuchak Weekend Market all make Bangkok a shoppers’ (and souvenir-hunter’s) dream. You’ll need to prepare yourself—Bangkok is intense. But for travellers craving local secrets and 24/7 energy, there’s nowhere in the world quite like it", content: 'Revved up at all hours, Bangkok remains one of the most intense places on Earth', imgUrl: 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/17/6d/df/ec/fireworks-yao-rooftop.jpg?w=300&h=300&s=1'},
    {id: 11, title: 'Taipei,Taiwan',des:"The bustling metropolis of Taipei is where you’ll find shiny skyscrapers and ancient temples hazy with incense standing side by side. Spend your day taking in the view from up above at the Taipei 101 before shopping your way down the streets of Ximending (with a bubble tea in hand, of course). As night falls, eat your way across the numerous night markets. From the XXL fried chicken cutlets to the stinky tofu, the street food here is addictive and will leave you hankering for more.", content: 'A city where gleaming modernity and ancient culture meet', imgUrl: 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/1b/33/f3/33/caption.jpg?w=300&h=300&s=1'},
    {id: 12, title: 'Kyoto,Japan', content: 'A passageway to Japans past, full of World Heritage sites and traditional arts',des:"The shrines and temples of Kyoto offer a rare link between modern life in the city and its very ancient past. The Shimogamo Shrine dates to the 6th century and seems suspended in time, its serenity and spiritual power still palpable. Visit Fushimi Inari Shrine, then see the life-sized Thousand Armed Kannon statues of Sanjūsangen-dō. Take in traditional geisha performances, then savor a tranquil meal at a restaurant overlooking the Kamo River.", imgUrl: 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/0e/62/c3/88/caption.jpg?w=300&h=300&s=1'},
    {id: 13, title: 'Tokyo,Japan', content: 'A nonstop city of thrilling contrasts', imgUrl: 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/1c/7c/eb/cb/photo0jpg.jpg?w=300&h=300&s=1' ,des:"With its futuristic skyscrapers, unrivalled food scene, and wild nightlife, Tokyo is a rush of pure adrenaline. This vast and multifaceted city is famously cutting edge, yet its ancient Buddhist temples, vintage teahouses, and peaceful gardens offer a serene escape — and a poignant reminder of the city’s long history. And for those who know where to look, Tokyo’s smaller pleasures (secret ramen spots, shopping alleys, chill record bars) are often hiding in plain sight."},
    {id: 14, title: 'Singapore,Singapore', content: 'Small in size, the ‘Lion City’ offers big delights', imgUrl: 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/1c/29/d4/40/night-view-of-the-hsbc.jpg?w=300&h=300&s=1',des:"This tiny island city-state is a study of fusions and contrasts bursting with wonders waiting to be explored. Tranquil parks abut futuristic skyscrapers and luxe shopping centres. A thriving street food scene and world-class restaurants offer countless ways to taste and sip your way through Singapore’s culinary melting pot. Your first trip to Singapore will prove that sometimes the best things come in small packages."},
    {id: 15, title: 'Seoul,South Korea', content: 'The business and cultural hub of South Korea, where skyscrapers tower over palaces and pagodas', imgUrl: 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/15/7b/23/c5/photo2jpg.jpg?w=300&h=-1&s=1',des:"From modern skyscrapers and neon lights to Buddhist temples, palaces and pagodas, Seoul is a fascinating mix of old and new. Take it all in from the N Seoul Tower, built atop a peak in Namsan Park. The teahouses and shops of Insadong give you a taste of Korean flavour, which you can further experience with a visit to the grounds and museums of Gyeongbokgung. UNESCO World Heritage Site Changdeokgung Palace is a fine example of authentic ancient architecture."},
    {id: 16, title: 'Bali,Indonesia', content: 'A tropical haven for beach bums, wellness worshipers, and the culturally curious', imgUrl: 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/17/2c/18/1f/photo9jpg.jpg?w=300&h=-1&s=1',des:"No island has enchanted travellers quite like Bali. Less than half the size of Hawaii’s big island, Bali manages to pack countless adventures into one small package. Dazzling beaches beckon the sun seekers and surfers along the island’s southwest coast, while ancient temples and a thriving wellness scene draw travellers inland to Ubud. It’s the kind of place where hedonists, relaxation-seekers, and ecotourists can all find something to enjoy, from wild nightclubs in Seminyak and Kuta to luxury clifftop hotels in Nusa Dua to the pristine jungles and volcanic landscapes of the island’s north."},
    {id: 17, title: 'Hong Kong,China', content: 'A vibrant harbour city with an unbeatable food scene', imgUrl: 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/14/24/ab/ea/a-cruise-in-victoria.jpg?w=300&h=300&s=1',des:"Delectable dim sum, floating islands, and a one-of-a-kind skyline are just some of Hong Kong’s enchanting features. Eat your way across Temple Street Night Market with its fish balls and stinky tofu, or settle in for dim sum at Michelin-starred venues like Tim Ho Wan. For traditional Chinese architecture, head to Ngong Ping Village, then take the tram to the tippity-top of Victoria Peak for skyscraper views. The gentle hills of Nan Lian Garden will deliver serenity, but a detour through the city’s cocktail bars will bring back Hong Kong’s urban buzz."},
    {id: 18, title: 'Goa,India', content: 'About Goa', imgUrl: 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/16/f7/a4/bd/baga-beach.jpg?w=300&h=300&s=1',des:"East meets West in this sun-soaked state, where Indian culture intertwines with Portuguese influences left over from a 500-year occupation. The beaches have long served as a magnet for serene hedonists. To the north, the tourist-centric scene is prevalent, with an international flair that is now skewing more hip than hippie. Travel south for stretches of unspoiled sand and an escape from large resorts. Temples, mosques and wildlife sanctuaries provide diversions from the beach."},





  ],
 "global":[
    {id: 19, title: 'The best new things to do in Japan', des:"The Land of the Rising Sun is ready to shine once again. After years of COVID closures, Japan has fully reopened its borders to international tourists. Visa exemptions have been restored for 68 countries including the United States, and PCR tests are no longer necessary with proof of three vaccinations. Bear in mind that masks are still ubiquitous indoors and on public transportation, and some businesses may require you to wear one.First-time and returning travelers alike will find new things to experience, and the favorable dollar-to-yen exchange rate means that there’s never been a better time to visit. Below, we’ve listed our favorite new hotels, restaurants, and attractions in Tokyo, Kyoto, and Osaka, as well as a can’t-miss installation on the art-centric island of Naoshima.", imgUrl: 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/26/ff/64/b3/b1e43685-a4e8-4163.jpg?w=400&h=300&s=1'},
    {id: 20, title: 'Bangkok hotels that highlight Thailands ', content: 'From century-old mansions to rustic bungalows right on the riverfrom $1300 per adult', imgUrl: 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/26/ff/65/7b/3f7b9f66-88a6-40e8.jpg?w=400&h=300&s=1',des:"Bangkok is one of the most-visited capital cities in the world, famed for its spicy street eats and well-priced spas as much as its colorful longtail boats, ancient temples, and lively night markets. The city also offers an abundance of hotels to suit any traveler or budget, from plucky backpacker options that start at $10 per night to five-star villas with Michelin-starred dining. If the bounty of Bangkok's options seems overwhelming, you certainly wouldn’t be the first travel planner to fall down a rabbit hole of choices. One of the best ways to forge a deeper connection with Bangkok is by staying in hotels that honor the city’s iconic architecture. Some are set in old Thai villas, made from weathered teak with iconic sloped, tiled roofs to funnel the rain away in monsoon season. The more classic river bungalows perch on stilts, and several of the narrow Chinese shophouses have been revamped into chic apartments. You can even overnight in the city’s former publishing mansion.  Ahead, you’ll find seven of the most unique places to stay in Bangkok."},
    {id: 21, title: 'A day trip to the Blue Mountains from Sydney', content: 'Things to do in the Blue Mountains', imgUrl: 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/1b/48/36/4f/caption.jpg?w=300&h=300&s=1',des:"No trip to Sydney is complete without an escape to the World Heritage-listed Blue Mountains National Park. Adventure beckons—with untouched natural wonders, dramatic scenery, majestic waterfalls, lush rainforests, scenic lookouts, grand canyons, and more.  You'll feel free as you ditch your digital devices and leave Sydney for trekking trails with mountain views and refreshing dips in waterholes.With so much to see and do, it can be difficult trying to fit everything into a one-day itinerary. If you’re keen on planning a day trip from Sydney to the Blue Mountains, we’ve compiled a handy guide with all the things you can do in a day."},
    {id: 22, title: 'A first-timer’s guide to Australia’s Kangaroo ', content: 'Where to play, eat, and stay—and how you can help the island recover from devastating bushfires', imgUrl: 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/26/ff/67/82/1d550793-c229-4d33.jpg?w=400&h=300&s=1',des:"One of the world’s great nature-based destinations, Kangaroo Island is just a 30-minute flight from Adelaide, but feels a million miles away from mainland Australia. Animals—including species found nowhere else in the world—outnumber people here, earning the island the nickname “Australia’s Galapagos.” Until 2020, a trip to Kangaroo Island meant untamed landscapes and close encounters with glossy black cockatoos, clusters of kangaroos, and koalas napping in eucalyptus trees. Then catastrophic bushfires swept the island, burning more than half the land and wiping out 40,000 animals, including several threatened species. Thankfully, Kangaroo Island has made an impressive comeback over the past two years—new-growth trees already stand at nearly half the height of those that burned, and wildlife populations are slowly recovering. The tourism industry has bounced back as well and is ready to welcome new visitors to the island. Below, we’ve rounded up the best places to play, eat, and stay on a visit to Kangaroo Island, plus how you can help the destination’s continued recovery efforts. "},
    {id: 23, title: 'Traveling to Singapore soon?', content: 'Traveling to Singapore soon? Here are some end-of-year events not to be missed', imgUrl: 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/26/ff/68/63/5a715c6a-4bb0-4e7b.jpg?w=400&h=300&s=1',des:"There’s plenty to do all year round in Singapore, but if you’ve picked to visit during this time of year, you’re in for a treat. Singapore’s calendar of events is packed to the brim with exciting activities for everyone of all ages—from the much-anticipated return of the Singapore Grand Prix to cultural festivals, exclusive art exhibitions, year-end Christmas celebrations, and Marina Bay Countdown with its spectacular fireworks display."},
    {id: 24, title: 'Maruku Arts ', content: '10 Indigenous experiences in Australia’s Northern Territory', imgUrl: 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/26/ff/69/3e/fa289785-e533-4c5e.jpg?w=400&h=300&s=1',des:"The Northern Territory (NT) is the best destination to learn about and experience the Indigenous culture. With so many Aboriginal tours available, it’s hard to pick a favorite. So here’s our round-up of the top cultural experiences to help you delve deeper into Indigenous Australia while visiting the NT. "},
    {id: 25, title: ' bucket list travel experiences in India', content: 'Looking for adventure? Check out these 8 incredible bucket list travel experiences in India that you should not miss out on this year.', imgUrl: 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/26/ff/6a/6a/28de9140-040f-453f.jpg?w=400&h=-1&s=1',des:"Varanasi, or Banaras, is a sacred city in northern India. It is a place of pilgrimage for Hindus, Buddhists, and Jains who come to bathe in the holy Ganges River. It is also known as the City of Temples and is home to many renowned writers. Whether it’s witnessing the evening Ganga Arti ceremony in a boat, exploring the ghats, or haggling for beautiful souvenirs, Varanasi will stay with you long after you’ve left the city."},
    {id: 26, title: 'must-try foods in South Korea', content: 'We partnered with Gangwon Province to bring you these five foods you can’t miss sampling on your next trip.', imgUrl: 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/26/ff/6b/8e/7007409e-e3ca-454a.jpg?w=400&h=-1&s=1',des:"With its vast coastline and thousands of acres of farmland, the Gangwon Province in South Korea is a favorite destination for foodies who crave fresh seafood, beef and chicken. But meat isn’t the only dish on the menu here. Gangwon-do is also home to a delicious assortment of tofu and noodle restaurants catering to the vegetarian diner."},
    {id: 27, title: 'gorgeous places in India ', content: 'awe-inspiring destinations that showcase the beauty and wonder of this vast, complex, and spiritual country.', imgUrl: 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/26/ff/6c/a6/fd1cbde3-5e7e-4084.jpg?w=400&h=-1&s=1',des:"If ever we were challenged to name a country more diverse than India, we’d have a tough time. Few places, if any, rival the sheer amount of traditions, cuisines, landscapes, and religions found within India’s borders, from the high Himalayas in the north to the desert sands of the west to the palm tree-fringed rivers and islands of the south. Here are 11 awe-inspiring destinations that showcase the beauty and wonder of this vast, complex, and spiritual country."},



  ],
  "beach":[
    {id: 28, title: 'Morocco,Amamia', des:"The Dominican Republic lies in the same waters as Cuba and Puerto Rico, taking up the eastern two-thirds of the island it shares with Haiti. Offering a lush interior with a mix of caves, Victorian gingerbread houses and the lore of pirates, plus 900 miles of coastline along its brim, island highlights include riding a cable car up Mount Isabel de Torres and basking on stunning Saona Island. Oh, and did we mention the D.R. is family-friendly, has just about perfect weather and is affordable?", content: 'About Dominican Republic', imgUrl: 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/21/65/5f/4b/caption.jpg?w=300&h=300&s=1&cx=1321&cy=849&chk=v1_14f7826859b4f964e5b2'},
    {id: 29, title: 'Miami,FL', content: 'About Miami', imgUrl: 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/1c/cd/04/e4/caption.jpg?w=300&h=300&s=1',des:"Whether you're into sport, sunshine or salsa, Miami sizzles all year round with exciting entertainment venues and attractions, world-class hotels and restaurants, great beaches and a nightlife that never sleeps. While South Beach, with its hip nightclubs and pastel-hued buildings, gets all the press, other sections of Miami are just as hot and offer culture, recreation and more. Spend the day soaking in the sights and sounds of Little Havana or soaking up the rays at Haulover Beach Park. Explore the Art Deco District or take the children to the zoo. At the end of the day, chill out at one of the area's bars and nightclubs. In Miami at night, the day is just beginning."},
    {id: 30, title: 'Hawai', content: 'The poster child of tropical holidays', imgUrl: 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/1b/33/f4/70/caption.jpg?w=300&h=300&s=1',des:"For many, the word holiday conjures images of sunbathing on a sunny beach, paddling in a dazzling blue ocean, napping under coconut trees—in other words, Hawaii. But travellers who can pull themselves away from the 50th state's stunning beaches will find so much more. From volcanic landscapes to hidden waterfalls and epic expeditions, a Hawaiian getaway can go in a dozen different directions. Each of the six major islands–Kauai, Oahu, Molokai, Lanai, Maui, and the island of Hawaii–has its own distinct personality and unique opportunities for adventure, dining, culture, and relaxation."},
    {id: 31, title: 'Tenerife,Spain', content: 'A popular resort destination thats still true to its roots', imgUrl: 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/1b/33/f7/dd/caption.jpg?w=300&h=300&s=1',des:"Despite being the most popular and developed of the Canary Islands, Tenerife still shows influence from the aboriginal Guanches people. Come in February, and you'll see a carnival celebration whirling through the streets, with enough feathers and sequins to give Rio a run for its money. Visitors clamber to conquer Mount Teide (Spain’s tallest peak) and to stretch out on the sands of Los Gigantes. Squawk hello to the playful parrots of Loro Park, or brave the petrifying drive to beautiful Masca Valley. For a true taste of Terenife, sample fresh farmhouse cheese and local bananas. A piece of delicate calado canario lace makes a special souvenir."},
    {id: 32, title: 'Martyle Beach,SC', content: 'Breezy seaside fun-in-the-sun with a side of Carolina BBQ.', imgUrl: 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/1c/bf/69/b0/caption.jpg?w=300&h=300&s=1',des:"As a popular spring-break destination, golfing hub, and beloved family holiday spot—Myrtle Beach is the happy place for a range of travellers. Take in a foot-stomping show at the Carolina Opry, soak up the sunbeams on the Grand Strand's many beaches, or mingle with the fishermen of Springmaid Pier. Those seeking high-energy fun can hit theme-park rides or wildlife tours, but it's also just as easy to spend an afternoon strolling around the boardwalk, ice cream in hand. Whatever your speed, you'll want to make frequent pit-stops to sample Carolina barbeque."},
    {id: 33, title: 'Bora Bora,French Polynesia ', content: 'About Bora Bora', imgUrl: 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/13/60/b0/bd/bora-bora.jpg?w=300&h=300&s=1',des:"The relatively small island of Bora Bora is an activity giant, offering visitors the chance to experience a 4x4 safari, sunbathe and swim at white sandy beaches, dive in a natural underwater park among fish and corals, experience thrilling shark feedings, or circle the turquoise lagoon by boat. And Bora Bora is a superlative romantic spot. Fall captive to this lush gem of a Polynesian island by sharing an intimate midnight dinner on the beach; visiting the Lagoonarium, the Diving Centre, the Coral Gardens or the Leopard Rays Trench; or taking it all in from the lofty heights of 2,300-foot Mount Otemanu."},
    {id: 34, title: 'Jain Spiritual Tour', content: 'from $6000 per adult', imgUrl: 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/1b/40/48/d3/caption.jpg?w=300&h=300&s=1'},
    {id: 35, title: 'Tulum,Mexico', content: 'About Tulum', imgUrl: 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/21/66/68/f6/caption.jpg?w=300&h=300&s=1&cx=988&cy=664&chk=v1_d1b5b3f4c384c764b7e1',des:"Yes, Tulum may well be one of the most Instagrammed spots in Mexico, with plenty of smoothie stands and yoga retreats, but the Caribbean beach town is so much more. In between dips in the cerulean waters, you can hike through dense jungle and explore a subterranean river at LabnaHa Eco Park. Or tour the ancient Mayan ruins that tower over town. (Tulum was the last city inhabited by the indigenous group.) Or hop on an ATV for an off-roading adventure across the sugary sand dunes. And after all that heart-pumping activity, eat your heart out at the authentic mezcalerias, low-key beach shacks, and celeb-chef, fine-dining spots."},
    {id: 36, title: 'Aruba', content: 'An island made for unplugging your devices and recharging your spirit', imgUrl: 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/1b/48/36/4f/caption.jpg?w=300&h=300&s=1',des:"The quintessential Caribbean island, Aruba is all sun and sea and stretches of powdery sand. Time slows to a languid pace here as you linger over a tropical drink or bob serenely in the water; only the parrotfish are in a hurry. Oranjestad's pastel facades of landmarks and shops boost the capital city's playful vibe. Scout out a shady hammock—the perfect spot for a nap—as the crashing waves of turquoise water create a soothing soundtrack."},




  ]



}

